# Generated by Django 2.0.1 on 2018-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('c_goods', '0007_auto_20180204_1047'),
        ('c_user', '0003_auto_20180202_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=None, to='c_goods.GoodInfo')),
                ('user', models.ForeignKey(on_delete=None, to='c_user.User')),
            ],
        ),
    ]
